---
- name: Cross-compile executable for RPi4
  hosts: blitzcrank

  tasks:
    - name: Build program
      ansible.builtin.command:
        argv:
          - crystal
          - build
          - --cross-compile
          - --target
          - aarch64-linux-gnu
          - -o
          - dist/card-switch
          - src/card-switch.cr
      delegate_to: localhost

    - name: Copy object
      ansible.builtin.copy:
        src: dist/card-switch.o
        dest: /tmp
        force: true

    - name: Link program
      ansible.builtin.command:
        argv:
          - cc
          - /tmp/card-switch.o
          - -o
          - /tmp/card-switch
          - -lpigpio
          - -lpcre2-8
          - -lm
          - -lgc
          - -lpthread
          - -levent
          - -lrt
          - -ldl

    - name: Remove object
      ansible.builtin.file:
        path: /tmp/card-switch.o
        state: absent

    - name: Move program to dietpi home
      ansible.builtin.copy:
        remote_src: true
        src: /tmp/card-switch
        dest: /home/dietpi
        owner: dietpi
        group: dietpi
        mode: '0755'
        force: true

    - name: Remove temp program
      ansible.builtin.file:
        path: /tmp/card-switch
        state: absent
